import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
  },
  display: {
    fontSize: 45,
    textAlign: 'center',
    padding: 10,
  },
  buttonRow: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginVertical: 5,
  },
  button: {
    backgroundColor: '#fff',
    borderRadius: 50,
    width: 80,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 8,
    marginRight: 4,
    marginBottom: 5,
    elevation: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  buttonText: {
    fontSize: 35,
    color: '#000',
  },
  buttonZero: {
    backgroundColor: '#fff',
    borderRadius: 50,
    width: 180,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 8,
    marginRight: 4,
    marginBottom: 5,
    elevation: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  operatorButton: {
    backgroundColor: '#f0f0f0',
    borderRadius: 50,
    width: 80,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 8,
    elevation: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  operatorButtonText: {
    fontSize: 35,
    color: '#ff9502',
  },
  equalsButton: {
    backgroundColor: '#ff9502',
    borderRadius: 50,
    width: 55,
    height: 70,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  equalsButtonText: {
    fontSize: 30,
    color: '#fff',
  },
  clearButton: {
    backgroundColor: '#f0f0f0',
    borderRadius: 50,
    width: '100%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
    elevation: 5,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  clearButtonText: {
    fontSize: 24,
    color: '#000',
  },
});
